version: '3.11'

services:
  api:
    container_name: meduzzen-backend-internship
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - backend
    command: >
      sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - backend
    volumes:
      - .:/app
    command: >
      sh -c "celery -A app.utils.celery_service worker --loglevel=warning --logfile=celery_worker.log"

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - backend
    volumes:
      - .:/app
    command: >
      sh -c "celery -A app.utils.celery_service beat --loglevel=warning --logfile=celery_beat.log"

volumes:
  postgres_data:
  redis_data:

networks:
  backend:
    driver: bridge
