version: '3.11'

services:
  api:
    container_name: meduzzen-backend-internship
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - backend
    volumes:
      - .:/app
    command: >
      sh -c "celery -A app.utils.celery_service worker --loglevel=warning --logfile=celery_worker.log"

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - backend
    volumes:
      - .:/app
    command: >
      sh -c "celery -A app.utils.celery_service beat --loglevel=warning --logfile=celery_beat.log"

networks:
  backend:
    driver: bridge
