"""cascade

Revision ID: 0205d8406615
Revises: aad265ea8728
Create Date: 2024-08-09 17:50:25.621062

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0205d8406615"
down_revision: Union[str, None] = "aad265ea8728"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("questions_quiz_id_fkey", "questions", type_="foreignkey")
    op.create_foreign_key(
        None, "questions", "quizzes", ["quiz_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint("quizzes_company_id_fkey", "quizzes", type_="foreignkey")
    op.create_foreign_key(
        None, "quizzes", "companies", ["company_id"], ["id"], ondelete="CASCADE"
    )
    op.create_unique_constraint(None, "results", ["id"])
    op.drop_constraint("results_quiz_id_fkey", "results", type_="foreignkey")
    op.drop_constraint("results_company_member_id_fkey", "results", type_="foreignkey")
    op.create_foreign_key(
        None,
        "results",
        "company_members",
        ["company_member_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None, "results", "quizzes", ["quiz_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "results", type_="foreignkey")
    op.drop_constraint(None, "results", type_="foreignkey")
    op.create_foreign_key(
        "results_company_member_id_fkey",
        "results",
        "company_members",
        ["company_member_id"],
        ["id"],
    )
    op.create_foreign_key(
        "results_quiz_id_fkey", "results", "quizzes", ["quiz_id"], ["id"]
    )
    op.drop_constraint(None, "results", type_="unique")
    op.drop_constraint(None, "quizzes", type_="foreignkey")
    op.create_foreign_key(
        "quizzes_company_id_fkey", "quizzes", "companies", ["company_id"], ["id"]
    )
    op.drop_constraint(None, "questions", type_="foreignkey")
    op.create_foreign_key(
        "questions_quiz_id_fkey", "questions", "quizzes", ["quiz_id"], ["id"]
    )
    # ### end Alembic commands ###
