"""add on delete cascade

Revision ID: 2af93f7320e2
Revises: c1c24264715b
Create Date: 2024-07-29 20:36:51.436646

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2af93f7320e2"
down_revision: Union[str, None] = "c1c24264715b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "actions", ["id"])
    op.drop_constraint("actions_user_id_fkey", "actions", type_="foreignkey")
    op.drop_constraint("actions_company_id_fkey", "actions", type_="foreignkey")
    op.create_foreign_key(
        None, "actions", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "actions", "companies", ["company_id"], ["id"], ondelete="CASCADE"
    )
    op.create_unique_constraint(None, "company_members", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "company_members", type_="unique")
    op.drop_constraint(None, "actions", type_="foreignkey")
    op.drop_constraint(None, "actions", type_="foreignkey")
    op.create_foreign_key(
        "actions_company_id_fkey", "actions", "companies", ["company_id"], ["id"]
    )
    op.create_foreign_key(
        "actions_user_id_fkey", "actions", "users", ["user_id"], ["id"]
    )
    op.drop_constraint(None, "actions", type_="unique")
    # ### end Alembic commands ###
