"""notif_user

Revision ID: 75ae14635b35
Revises: 1942f7c52175
Create Date: 2024-08-16 12:51:02.454330

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "75ae14635b35"
down_revision: Union[str, None] = "1942f7c52175"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_notifications", sa.Column("user_id", sa.UUID(), nullable=False))
    op.drop_constraint(
        "user_notifications_company_member_id_fkey",
        "user_notifications",
        type_="foreignkey",
    )
    op.create_foreign_key(None, "user_notifications", "users", ["user_id"], ["id"])
    op.drop_column("user_notifications", "company_member_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_notifications",
        sa.Column("company_member_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "user_notifications", type_="foreignkey")
    op.create_foreign_key(
        "user_notifications_company_member_id_fkey",
        "user_notifications",
        "company_members",
        ["company_member_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("user_notifications", "user_id")
    # ### end Alembic commands ###
