"""on delete company

Revision ID: 7cb657ffa5ab
Revises: e7c66db4623f
Create Date: 2024-08-05 13:53:44.034594

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7cb657ffa5ab"
down_revision: Union[str, None] = "e7c66db4623f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("companies_owner_id_fkey", "companies", type_="foreignkey")
    op.create_foreign_key(
        None, "companies", "users", ["owner_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "companies", type_="foreignkey")
    op.create_foreign_key(
        "companies_owner_id_fkey", "companies", "users", ["owner_id"], ["id"]
    )
    # ### end Alembic commands ###
