"""Init1

Revision ID: c2f403fc5396
Revises: 022c06bb9c4e
Create Date: 2024-07-07 13:07:46.044599

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c2f403fc5396"
down_revision: Union[str, None] = "022c06bb9c4e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("is_admin", sa.Boolean(), nullable=False))
    op.alter_column(
        "users",
        "username",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=50),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "email",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=50),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "password",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=100),
        existing_nullable=False,
    )
    op.drop_column("users", "avatar_url")
    op.drop_column("users", "refresh_token")
    op.drop_column("users", "roles")
    op.drop_column("users", "confirmed")
    op.drop_column("users", "is_active")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "users",
        sa.Column("confirmed", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "users",
        sa.Column(
            "roles",
            postgresql.ENUM("admin", "user", name="role"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "refresh_token", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "avatar_url", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
    )
    op.alter_column(
        "users",
        "password",
        existing_type=sa.String(length=100),
        type_=sa.VARCHAR(length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "email",
        existing_type=sa.String(length=50),
        type_=sa.VARCHAR(length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "username",
        existing_type=sa.String(length=50),
        type_=sa.VARCHAR(length=255),
        existing_nullable=False,
    )
    op.drop_column("users", "is_admin")
    # ### end Alembic commands ###
