"""add admin role

Revision ID: e5c5da6c8cf3
Revises: 2af93f7320e2
Create Date: 2024-07-30 13:27:48.802719

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e5c5da6c8cf3"
down_revision: Union[str, None] = "2af93f7320e2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("companies_owner_id_fkey", "companies", type_="foreignkey")
    op.drop_column("companies", "owner_id")
    op.alter_column("users", "password", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("users", "is_admin")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("is_admin", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.alter_column("users", "password", existing_type=sa.VARCHAR(), nullable=True)
    op.add_column(
        "companies",
        sa.Column("owner_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "companies_owner_id_fkey",
        "companies",
        "users",
        ["owner_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
