"""change field options

Revision ID: e7acdcb99832
Revises: 7cb657ffa5ab
Create Date: 2024-08-05 18:24:50.061012

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e7acdcb99832"
down_revision: Union[str, None] = "7cb657ffa5ab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "questions",
        sa.Column("answer_options", sa.ARRAY(sa.String(length=255)), nullable=False),
    )
    op.drop_column("questions", "options")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "questions",
        sa.Column(
            "options",
            postgresql.ARRAY(sa.VARCHAR(length=255)),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("questions", "answer_options")
    # ### end Alembic commands ###
