"""edit company member

Revision ID: e7c66db4623f
Revises: e87b14fb9e3b
Create Date: 2024-08-03 10:33:09.588307

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e7c66db4623f"
down_revision: Union[str, None] = "e87b14fb9e3b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "questions", ["id"])
    op.create_unique_constraint(None, "quizzes", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "quizzes", type_="unique")
    op.drop_constraint(None, "questions", type_="unique")
    # ### end Alembic commands ###
