name: Deploy to Amazon ECS

on:
  push:
    branches:
      - develop

jobs:
  setup-and-test:
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: develop

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run setup and tests on EC2 instance
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > /tmp/ec2-key.pem
          chmod 600 /tmp/ec2-key.pem

          ssh -o StrictHostKeyChecking=no -i /tmp/ec2-key.pem ubuntu@${{ secrets.EC2_PUBLIC_IP }} <<EOF
              cd internship_meduzzen_backend

              echo "Switching to the correct branch..."
              git fetch origin
              git checkout $BRANCH_NAME
              git pull origin $BRANCH_NAME

              echo "Stopping and removing existing containers..."
              docker-compose down || true

              echo "Building and running Docker Compose with the latest images..."
              docker-compose up -d --build

              docker-compose exec -T web poetry run pytest --maxfail=1 --disable-warnings -q -v
          EOF

  deploy:
    runs-on: ubuntu-latest
    needs: setup-and-test
    env:
      BRANCH_NAME: develop

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2 instance
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > /tmp/ec2-key.pem
          chmod 600 /tmp/ec2-key.pem

          ssh -o StrictHostKeyChecking=no -i /tmp/ec2-key.pem ubuntu@${{ secrets.EC2_PUBLIC_IP }} <<EOF
              cd internship_meduzzen_backend

              echo "Pulling latest code from git repository..."
              git fetch origin
              git checkout $BRANCH_NAME
              git pull origin $BRANCH_NAME

              echo "Stopping and removing existing containers..."
              docker-compose down || true

              echo "Building and running Docker Compose with the latest images..."
              docker-compose up -d --build
          EOF